Изменение структуры
andrey17895/SpringTest pull request #7
Opened 2019-11-26 12:07 UTC by andrey17895

2019-11-26 15:09 UTC, vdsimako requested changes

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/SpringTestApplication.java
> +@ComponentScan({"com.pflb.springtest"})
тебе idea не подсказывает, что эта аннотация лишняя и включена в аннотации SpringBootApplication

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/controller/FileUploadController.java
> +    private HistoryFileService historyFileService;
обычно поля классов ставят первыми потом конструктор потом методы

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/jms/consumer/RabbitMessagingListener.java
> +@ConfigurationProperties(prefix = "messaging")
не надо смешивать bean'ы спринга, сделай отдельный класс для пропертей и в отдельном классе создай бин по аналогии с modelmapper

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/service/HarParserService.java
>              System.out.println(e.getMessage());
почитай как писать логи, таким способом мало кто пользуется

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/service/RequestService.java
> +    private RequestRepository requestRepository;
приведи к однообразному способу dependency injection

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/service/TestProfileService.java
> +    private TestProfileRepository testProfileRepository;
приведи к однообразному способу dependency injection

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/jms/producer/RabbitJmsProducer.java
>      @Autowired
приведи к однообразному способу dependency injection

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/jms/consumer/RabbitMessagingListener.java
> +            System.out.println("Exception:" + e.getMessage());
причесать логгирование

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/jms/consumer/RabbitMessagingListener.java
> +                    RequestEntity requestEntity = new RequestEntity();
вместо кучки setter'ов лучше использовать builder

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/exception/ResourceNotFoundException.java
>      public ResourceNotFoundException(String s) {
Здесь можно завязываться на текст ошибки типа стриг, но лучше сделать enum с возможными текстами ошибок, и если надо подменять значение на основе шаблона

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/exception/ResourceNotFoundAdvice.java
> +package com.pflb.springtest.exception;
если это все модель то внеси все в один пакет model

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/entity/RequestEntity.java
>      @JsonIgnore
зачем здесь JsonIgnore?

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/dto/HarRequestDto.java
>      @JsonDeserialize(using = ListToMapDeserializer.class)
без десериализатора вроде работает

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/dto/HarRequestDto.java
>  @JsonIgnoreProperties(ignoreUnknown = true)
без дополнительных настроек ObjectMapper тоже прожевывает сущности

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/dto/HarPostDataDto.java
>  @JsonIgnoreProperties(ignoreUnknown = true)
без дополнительных настроек ObjectMapper тоже прожевывает сущности

2019-11-26 15:09 UTC, vdsimako commented on src/main/java/com/pflb/springtest/dto/HarLogDto.java
>  @JsonIgnoreProperties(ignoreUnknown = true)
без дополнительных настроек ObjectMapper тоже прожевывает сущности

2019-11-27 11:12 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/dto/HarRequestDto.java
>      @JsonDeserialize(using = ListToMapDeserializer.class)
В хар параметры и хедеры хранятся в виде списка [{"name":"name1", "value":"value1"}, ...].
Но если нужно могу перенести логику преобразования в сервис

2019-11-27 12:19 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/SpringTestApplication.java
> +@ComponentScan({"com.pflb.springtest"})
не подсказывает

2019-11-27 12:32 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/exception/ResourceNotFoundAdvice.java
> +package com.pflb.springtest.exception;
И advice, и само исключение?

2019-11-27 14:49 UTC, vdsimako commented on src/main/java/com/pflb/springtest/dto/HarRequestDto.java
>      @JsonDeserialize(using = ListToMapDeserializer.class)
лучше в сервисе - объекты должны показывать реальную структуру

2019-11-27 14:49 UTC, vdsimako commented on src/main/java/com/pflb/springtest/SpringTestApplication.java
> +@ComponentScan({"com.pflb.springtest"})
![image](https://user-images.githubusercontent.com/15703327/69733377-4c104280-113e-11ea-821e-ed5dba8687f7.png)

2019-11-27 14:53 UTC, vdsimako commented on src/main/java/com/pflb/springtest/exception/ResourceNotFoundAdvice.java
> +package com.pflb.springtest.exception;
advice это логика mvc - оставь с контроллерами

2019-11-28 11:49 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/SpringTestApplication.java
> +@ComponentScan({"com.pflb.springtest"})
убрал

2019-11-28 11:49 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/controller/FileUploadController.java
> +    private HistoryFileService historyFileService;
Поправил

2019-11-28 11:49 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/jms/consumer/RabbitMessagingListener.java
> +@ConfigurationProperties(prefix = "messaging")
выделил конфигурационный бин

2019-11-28 11:50 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/dto/HarRequestDto.java
>      @JsonDeserialize(using = ListToMapDeserializer.class)
поравил

2019-11-28 11:50 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/dto/HarRequestDto.java
>  @JsonIgnoreProperties(ignoreUnknown = true)
убрал

2019-11-28 11:53 UTC, andrey17895 commented on src/main/java/com/pflb/springtest/service/HarParserService.java
>              System.out.println(e.getMessage());
переделал

2019-11-28 12:18 UTC, vdsimako commented
надо сделать rebase на master ветку

2019-11-28 12:20 UTC, vdsimako commented on src/main/java/com/pflb/springtest/jms/consumer/RabbitMessagingListener.java
> +@ConfigurationProperties(prefix = "messaging")
отдельный класс @Configuration - в котором создаются bean 
отдельный класс который работает с пропертями

2019-11-28 12:22 UTC, vdsimako commented on src/main/java/com/pflb/springtest/service/HarParserService.java
>              System.out.println(e.getMessage());
почитай как использовать Log4j2

2019-11-28 12:28 UTC, vdsimako reviewed
надо сделать rebase на master ветку  

- [x] убрать неиспользуемые классы 

- [x] убрать закомментированный код

2019-11-28 13:22 UTC, vdsimako approved these changes

2019-11-28 13:22 UTC, closed without merging